apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zbvbl3hkt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zbvbl3hkt-java-quarkus-gitops